### ISSUE TITLE
Plugin failed to work on 4.14

### ISSUE THREAD

**Issue by raoul95** [EverNewJoy/VictoryPlugin#17]
i have downloaded your victory plugin ,when i tried it on 4.14 it shows incompatible ,when i tried to rebuild using VS it shows msb 3705 error,what the fix?
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2660	'UPrimitiveComponent::K2_LineTraceComponent': function does not take 8 arguments	Pluginnn	D:\Pluginnn\Plugins\VictoryPlugin-master\Source\VictoryBPLibrary\Private\VictoryBPFunctionLibrary.cpp	3230	
Error	C2660	'UPrimitiveComponent::K2_LineTraceComponent': function does not take 8 arguments	Pluginnn	D:\Pluginnn\Plugins\VictoryPlugin-master\Source\VictoryBPLibrary\Private\VictoryBPFunctionLibrary.cpp	3302	
Error		Failed to produce item: D:\Pluginnn\Plugins\VictoryPlugin-master\Binaries\Win64\UE4Editor-VictoryBPLibrary-283.dll	Pluginnn	D:\Pluginnn\Intermediate\ProjectFiles\ERROR	1	
Error	MSB3075	The command "D:\4.14\Engine\Build\BatchFiles\Build.bat PluginnnEditor Win64 Development "D:\Pluginnn\Pluginnn.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.	Pluginnn	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	41	
`

**Comment by EverNewJoy** [comment]
Plugin is now on 4.15 :)
