### ISSUE TITLE
"Load Texture 2D from File" Node is not calculating the Mip Map correctly

### ISSUE THREAD

**Issue by manuganu9** [EverNewJoy/VictoryPlugin#2]
I'm trying to set material onto object at run-time.

I'm creating material from texture & displacement map image file.  These image files are loading from folder using Victory Plugin's "Load Texture 2D from File" Node.

I'm creating the material instance dynamic of the "test material". Now I'm setting the texture and displacement parameter as shown in figure [4](My texture and displacement map image resolution is **512x512**).
After creating material instance dynamic, I'm setting this material to the object.

figure[1] test material: http://imgur.com/PHlU0TA
figure[2]  texture: http://imgur.com/6YmZ4ea
figure[3]  displacement map: http://imgur.com/iGDYsrS
figure[4]  Method: http://imgur.com/PQZ9C3a

Now here is the problem.

When I directly create material in material editor from texture and displacement map and set it onto object. It doesn't generate*\* moiré pattern.**

But when I run-time set the material onto object using figure [4]. It will generate moiré pattern.

Here are the sample screen shots of both.

figure[5]: Material Editor result: http://imgur.com/nKan9eK
figure[6]: Runtime result: http://imgur.com/ao2XnDk

I think the "Load Texture 2D from File" Node is not calculating the Mip Map correctly.

**Comment by EverNewJoy** [comment]
Mip map data can't be properly calculated from raw pixel data, the mip map code is engine side, if you find a way let me know!
