### ISSUE TITLE
Compile Problem.

### ISSUE THREAD

**Issue by FinalSparkGamestudios** [EverNewJoy/VictoryPlugin#22]
Plugins/VictoryPlugin/Source/VictoryBPLibrary/Public/VictoryBPFunctionLibrary.h(1800): error : 'GetTimeAlive' conflicts with 'Function /Script/VictoryBPLibrary.VictoryBPFunctionLibrary:GetTimeAlive'.

The error should tell you enough. I fixed it by renaming the function to something else.

**Comment by EverNewJoy** [comment]
that was an error caused by Kris's pull request,I fixed locally but never uploaded
