### ISSUE TITLE
Unable to get the nodes of Plugin in MAC.

### ISSUE THREAD

**Issue by L34D3R** [EverNewJoy/VictoryPlugin#23]
I put the VictoryPlugin in the Plugins Folder. After that I compiled it from the XCode.
When I open the project, I'm able to see the plugin in the plugin window. But I'm not able to get any nodes of plugin in Level Blueprint. Even I did't find VictoryBPLibrary Category in the Level Blueprint.

Here are the  @screenshots.
![untitled1](https://cloud.githubusercontent.com/assets/13694300/24826628/06fd5b20-1c58-11e7-81b1-9e9c0be4ee67.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/13694300/24826630/1449e32a-1c58-11e7-9372-93dbacfc9505.png)

**Comment by EverNewJoy** [comment]
I have multiple users who have successfully compiled for mac, the only prerequsite they mentioned being required was to including the plugin in their build cs public dependencies list.

Please try that if you haven't already to ensure a full compile for mac :)

Also let me know if it worked so others will know too :)

Rama

**Comment by zeebok** [comment]
I was having a similar issue on Linux, and my solution was to make sure it was in the build cs dependency list and also remove the whitelist from the uplugin. It shows and works great, so thanks for the great plugin!

**Comment by EverNewJoy** [comment]
Your welcome @zeebok !

:)

Rama

**Comment by XiaoyShow** [comment]
> I was having a similar issue on Linux, and my solution was to make sure it was in the build cs dependency list and also remove the whitelist from the uplugin. It shows and works great, so thanks for the great plugin!

  @zeebok hello,  i meet the same issue, where is the build cs dependency list? Thank you~

**Comment by zeebok** [comment]
> > I was having a similar issue on Linux, and my solution was to make sure it was in the build cs dependency list and also remove the whitelist from the uplugin. It shows and works great, so thanks for the great plugin!
> 
> @zeebok hello, i meet the same issue, where is the build cs dependency list? Thank you~

It appears the Build.cs file has changed significantly since I used it so I am not sure I can be of much help. This is something @EverNewJoy would have to speak to.
