### ISSUE TITLE
Support for UE 4.15

### ISSUE THREAD

**Issue by Nixellion** [EverNewJoy/VictoryPlugin#24]
It seems they changed location of ImageWrapper in 4.15, details here:
https://answers.unrealengine.com/questions/374166/411p5-what-happened-to-iimagewrapperh.html

I tried changing that, one error was gone, but got more errors. I guess there were several api changes. Hope someone will find time to fix this soon :)

**Comment by EverNewJoy** [comment]
Image wrapper issue has been fixed, thanks for stopping by :)
