### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by teak421** [EverNewJoy/VictoryPlugin#28]
Hi.  When I compile the latest (4.17) Victory Plugin I am getting the error in the screenshot.  Also attached is the RunUAT.bat file that I used to compile.  I do this so when I create new projects the plugin is available and ready... No need to compile or add per-project.. allows for BP only projects..  FYI, this method worked for the previous version.

Please let me know if you want me to try anything... Thanks.

[RunUAT.zip](https://github.com/EverNewJoy/VictoryPlugin/files/1203935/RunUAT.zip)

![victoryerror](https://user-images.githubusercontent.com/13898029/29013259-c2480e50-7af6-11e7-92a0-bfad1bf58c5d.PNG)

**Comment by EverNewJoy** [comment]
Those are all errors for things that are present in 4.17, but not in 4.16, are you sure you are compiling with 4.17 engine build?

I just packaged new 4.17 build with no issues using UE4 marketplace workflow so I am feeling pretty good about the 4.17-ness of the current build, but 4.16 not compatible with current source code.

♥

Rama

**Comment by teak421** [comment]
Oh my goodness, that's the issue!  Apologies... Closing issue.
