### ISSUE TITLE
4.18 Compile

### ISSUE THREAD

**Issue by Bdoom** [EverNewJoy/VictoryPlugin#32]
2>E:\myproj (2)\myproj\Plugins\VictoryPlugin\Intermediate\Build\Win64\UE4Editor\Inc\VictoryBPLibrary\VictoryBPFunctionLibrary.gen.cpp(258): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>E:\myproj(2)\myproj\Plugins\VictoryPlugin\Intermediate\Build\Win64\UE4Editor\Inc\VictoryBPLibrary\VictoryBPFunctionLibrary.gen.cpp(258): error C2146: syntax error: missing ';' before identifier 'UClass'
2>E:\myproj (2)\myproj\Plugins\VictoryPlugin\Intermediate\Build\Win64\UE4Editor\Inc\VictoryBPLibrary\VictoryBPFunctionLibrary.gen.cpp(8006): error C2065: 'Z_Construct_UClass_UDestructibleComponent_NoRegister': undeclared identifier
2>

**Comment by Stormwind99** [comment]
See #35
