### ISSUE TITLE
Error compiling 4.18 Preview 2, VS 2017

### ISSUE THREAD

**Issue by DotBow** [EverNewJoy/VictoryPlugin#35]
Error compiling header:
Unrecognized type 'UDestructibleComponent' - type must be a UCLASS, USTRUCT or UENUM	UE_Expresome	E:\Expresome\UE_Expresome\Plugins\VictoryPlugin\Source\VictoryBPLibrary\Public\VictoryBPFunctionLibrary.h	401

**Comment by DotBow** [comment]
Just need to enable APEX plugin to fix this. Is it including in packaging to game if I'am not using it?

**Comment by DotBow** [comment]
Just need to enable APEX plugin to fix this. 
But anyway more other errors...
Is it including in packaging to game if I'm not using it?

**Comment by Burnrate** [comment]
Did you find out anything else about this?  I have APEX in my public dependency modules but it's still not happy.

**Comment by EverNewJoy** [comment]
I haven't done a 4.18 build yet, but if anyone has they are welcome to post a pull request :)

Rama

**Comment by Stormwind99** [comment]
@EverNewJoy - apparently I still have repo commit access since helping you set up the repo - because I meant to submit a pull request for my UE4.18.0 changes but I pushed to the repo instead and it allowed it.  Sorry!

Anyway, the plugin builds under UE4.18.0 now - but I have only started testing.

**Comment by EverNewJoy** [comment]
" apparently I still have repo commit access since helping you set up the repo"

Haha you earned it!  Thanks so much! This really helps me out! I was travelling so couldn't do it myself.

♥

Rama
