### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by n1ckfg** [EverNewJoy/VictoryPlugin#43]
I'd like to redistribute this in an open-source project; can you include a license? Suggest the MIT license if you don't have a preference: https://github.com/n1ckfg/KinectToPin/blob/master/license.txt

**Comment by EverNewJoy** [comment]
Hi there @n1ckfg !

You are welcome to use my plugin as long as you mention its origin and include link to this github and/or my website www.ue4code.com

Have fun!

♥

Rama

**Comment by n1ckfg** [comment]
Thanks!
