### ISSUE TITLE
i get an error on 4.19

### ISSUE THREAD

**Issue by davedumas0** [EverNewJoy/VictoryPlugin#45]
![error_01](https://user-images.githubusercontent.com/20492304/37857659-35885240-2eba-11e8-871e-23d1700e87f1.png)
![error_02](https://user-images.githubusercontent.com/20492304/37857661-37c86036-2eba-11e8-8cdc-15d349f64fd3.png)
 am i installing it wrong ?

**Comment by davedumas0** [comment]
i got it working  before i enabled your plugin i had to enable that ApexDestruction plugin manually (for others with the same issue the ApexDestruction plugin is in the collision category) after that restart editor then enabled your plugin and everything works fine

**Comment by EverNewJoy** [comment]
ahh thanks for that, I've now updated the main upload

:)

Rama
