### ISSUE TITLE
Problem with VictoryPlugin 4.20

### ISSUE THREAD

**Issue by NerofleLincoln** [EverNewJoy/VictoryPlugin#49]
Hi, i downloaded the plugin and i did everything right but i can't use the plugin. Error message is like "not the good version". I'm on UE4 4.20.2. Can you help me ?

**Comment by cookiedragon234** [comment]
I get the same, "The following modules are missing or built with a different engine version: VictoryBPLibrary Would you like to rebuild them now?" Rebuilding results in an error. Does anyone know how to fix this?

**Comment by Starkium** [comment]
rebuild them in visual studio. this is the source build. If you want the prebuilt binaries you need to go to the download links on the forum post.

If you want to rebuild this then you need to make sure your project supports c++. If it is only a blueprint project, open it up without the plugin in the folder, then inside your content browser add new c++ class, you can leave all the defaults. it will compile etc. save and close project, then add the plugin to the plugins folder, then go to the exe for your project, right click and generate project files, then open the visual studio solution file, should be purple, then build the project from there. Should work.

**Comment by EverNewJoy** [comment]
Thank you for replying @Starkium
