### ISSUE TITLE
Incorrect directory referenced?

### ISSUE THREAD

**Issue by Starkium** [EverNewJoy/VictoryPlugin#54]
I've not had this issue with victory library yet, but I am on a source engine build now. For some reason, even though the victory library is in my project plugins folder, it thinks it's trying to reference "U:\Engines\UnrealEngine-4.21\UnrealEngine-4.21\Engine\Source\VictoryBPLibrary\Public" 
instead of 
"U:\Projects\DungeonMaster\Plugins\VictoryPlugin\Source\VictoryBPLibrary\Public"

Maybe we should get the path similarly to how the VR Expansion library does for the run time folder, example below:

private string PluginsPath
    {
        get { return Path.GetFullPath(Target.RelativeEnginePath) + "Plugins/Runtime/"; }
    }

This seems like a safer solution. Just my two cents. Maybe I'll do a pull request.

**Comment by EverNewJoy** [comment]
Thank you for the comment and info, I hope everything is working great for you now :)
