### ISSUE TITLE
VictoryBPFunctionLibrary.cpp 4.23 compatability

### ISSUE THREAD

**Issue by KabusDev** [EverNewJoy/VictoryPlugin#58]
![image](https://user-images.githubusercontent.com/14855031/61566409-f8953600-aa73-11e9-890f-d4b22c17c120.png)

There was a change in the recent code for the Unreal Engine 4.23 pre-release, the branch's changes show that both ActionMappings and AxisMappings are now private, new public functions have been added.

[Link to commit with InputSettings.h & InputSettings.cpp Changes](https://github.com/EpicGames/UnrealEngine/commit/bcc5bcf128a758f0de72c4e460a16423a200d915#diff-6a66c55e3031f6dbfe78bcbe366f045d)

**Comment by Firefly74940** [comment]
fixed in https://github.com/EverNewJoy/VictoryPlugin/pull/60

**Comment by EverNewJoy** [comment]
Thank you @Firefly74940 !

♥

Rama
