### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Bubeboi** [EverNewJoy/VictoryPlugin#59]
So, I extract the folder, and put it into the directory E:\Program Files\Epic Games\UE_4.22\Engine\Plugins\Marketplace And then I load up the Epic Games launcher, and see nothing. Is that the wrong directory? And I have looked around and I see no guide on where to put the folder in, or how to install it. Help would be appreciated! Thanks.

-Bubeboi

**Comment by campmdabt** [comment]
If you're adding it to the binary version of the engine, you need to get the pre-compiled plugin from forum linked [here](https://forums.unrealengine.com/development-discussion/blueprint-visual-scripting/4014-39-rama-s-extra-blueprint-nodes-for-you-as-a-plugin-no-c-required). The 4.22 version is currently [here](https://www.mediafire.com/file/87hgnyqojdi1pen/VictoryPlugin422.zip/file).

**Comment by Bubeboi** [comment]
Ok. Thanks!

**Comment by Bubeboi** [comment]
@campmdabt Ok, thanks! I put it into the directory into a folder called the same as the .zip How do I install it onto my engine now? Sorry if I am being ignorant.

**Comment by campmdabt** [comment]
If you have these files in the same location: 

![image](https://user-images.githubusercontent.com/15316009/63981318-9d039280-ca8c-11e9-94a6-df9063030e14.png)

You should be able to open up UE4 and check the plugins:

![image](https://user-images.githubusercontent.com/15316009/63981430-11d6cc80-ca8d-11e9-9de4-1db57104e8a4.png)

**Comment by EverNewJoy** [comment]
Thank you Cameron for helping out in this thread :)

♥

Rama

**Comment by Bubeboi** [comment]
Yep! Thanks! :)

**Comment by Bubeboi** [comment]
Hmmmm I have opened, and closed Unreal Engine several times and it has not showed up in my plugins tabs.

**Comment by Bubeboi** [comment]
@campmdabt do you know why it's not showing up? Even after I added the plugin and restarted Unreal multiple times?

**Comment by campmdabt** [comment]
Snip the folder location and files like I did, and also show me the link where you got the files from.

**Comment by Bubeboi** [comment]
K

**Comment by Bubeboi** [comment]
Ok the location is E:\Program Files\Epic Games\UE_4.22\Engine\Plugins\Marketplace
![image](https://user-images.githubusercontent.com/43781076/64081113-75017280-ccca-11e9-9626-b38ff96e8cff.png)
and then I downloaded from this link:
https://www.mediafire.com/file/87hgnyqojdi1pen/VictoryPlugin422.zip/file

**Comment by campmdabt** [comment]
Can you show the contents of the VictoryPlugin folder? I want to make sure everything is there, especially the .uplugin file. After that, head over to E:\Program Files\Epic Games\UE_4.22\Engine\Binaries\Win64\Ue4editor.exe and open the editor from there to make sure that is the engine that is actually opening. Then create a new project using that editor, wait till it opens, and check the installed plugins.

**Comment by Bubeboi** [comment]
Uhhh ok so

**Comment by Bubeboi** [comment]
Wait

**Comment by Bubeboi** [comment]
Bruh moment I forgot to mention I am using a version of Flex

**Comment by Bubeboi** [comment]
Ok I am putting the folder in the flex directory

**Comment by Bubeboi** [comment]
I'll tell you what it does

**Comment by Bubeboi** [comment]
Eyyyyyy thanks man you the best
![image](https://user-images.githubusercontent.com/43781076/64132539-93d13900-cd9e-11e9-9d81-962f103ddabe.png)
