### ISSUE TITLE
WidgetGetParentOfClass fails if immediate parent is UserWidget

### ISSUE THREAD

**Issue by rcywongaa** [EverNewJoy/VictoryPlugin#9]
Steps to reproduce:
Create a `UserWidget` called `MyWidget`
Create another `UserWidget` called `MyWidget2`
Remove the default `canvas panel` from `MyWidget2` and add `MyWidget` to it
Inside Graph of `MyWidget2`, use `WidgetGetParentOfClass(MyWidget2, UserWidget)`

Expected results: `WidgetGetParentOfClass` should return `MyWidget`
Actual results: `WidgetGetParentOfClass` returns null

Cause: On line 5109, `ChildWidget->GetParent()` returns null since the parent is a `UserWidget` hence the loop on line 5113 is never entered hence never using `GetOuter()` to reach `MyWidget`

Suggested fix has been submited with pull request can be found at https://github.com/EverNewJoy/VictoryPlugin/pull/10

**Comment by EverNewJoy** [comment]
author fixed this in recent pull request far as I know <3 Rama
