### ISSUE TITLE
Why do this? 

### ISSUE THREAD

**Issue by nonlin** [EverNewJoy/VictoryPlugin#90]
Below this code (comment linked below), why do you flip R and B? 

https://github.com/EverNewJoy/VictoryPlugin/blob/4a05929b718dd14f47a0a949481ae8f7c21d2eaa/Source/VictoryBPLibrary/Private/VictoryBPFunctionLibrary.cpp#L5024

**Comment by Downchuck** [comment]
I think a few lines above you can see the input data is in BRGA, so this just accommodated that.
